# Generated by Django 5.0.1 on 2024-01-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('spot_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('perp_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quart_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('spread', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
